
- repo_name
- url
- pulls_count
- issues_count
- commits_count
- branches_count
- releases_count
- owner_type
- watchers_count
- forks_count
- stargazers_count
# - age
- development_time
- max_days_without_commit
- owner_account_age
- avg_dev_account_age
# - documentation_changes_frequency
# - documentation_changes_additions
- has_test
- has_doc
- has_example
- has_readme
- owner_projects_count
- owner_following
- owner_followers
- devs_followers_avg
- devs_following_avg
- commits_by_dev_with_most_commits
- magnetism
- stickiness
- wealth
- last_commit_age
#- health
