
end_condition: 'Maintained'
end_value: 200
from_year: '2011'
to_year: '2019'

maintained_ids: 'maintained_ids.dat'
unmaintained_ids: 'unmaintained_ids.dat'
not_suitable_ids: 'not_suitable_ids.dat'
maintained_csv_file: 'maintained.csv'
unmaintained_csv_file: 'unmaintained.csv'
features_file: 'configs/features.yml'

s3_region: 'us-west-2'
